name: Restock Watch
permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch: {}

jobs:
  watch:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
poll_interval_seconds: 120
timeout_seconds: 20
user_agent: "RestockWatch-GHA/1.0"

targets:
  - name: "Pokémon Center – Phantasmal Flames Elite Trainer Box"
    url: "https://www.pokemoncenter.com/product/10-10186-109/"
    parse:
      mode: "contains"
      in_stock_contains: ["Add to Cart","Add to Bag"]
      out_of_stock_contains: ["Out of Stock","Sold Out"]

  - name: "Target – Twilight Masquerade Elite Trainer Bundle"
    url: "https://www.target.com/p/blaze/-/A-91619960?clkid=e16ce7a3N89d711f0b1e7c13254943ab0&cpng=&TCID=AFL-e16ce7a3N89d711f0b1e7c13254943ab0&lnm=81938&afid=Mavely&ref=tgt_adv_xasd0002"
    parse:
      mode: "regex"
      pattern_in_stock: "(Add\\s*to\\s*cart|Pickup\\s*here)"
      pattern_out_of_stock: "(Sold\\s*out|Unavailable)"

  - name: "PC – Obsidian Flames ETB"
    url: "https://www.pokemoncenter.com/product/186-85392/pokemon-tcg-scarlet-and-violet-obsidian-flames-pokemon-center-elite-trainer-box"
    parse:
      mode: "contains"
      in_stock_contains: ["Add to Cart","Add to Bag"]
      out_of_stock_contains: ["Sold Out","Out of Stock"]

  - name: "PC – Prismatic Evolutions Binder Collection"
    url: "https://www.pokemoncenter.com/product/10-10023-101/pokemon-tcg-scarlet-and-violet-prismatic-evolutions-binder-collection"
    parse:
      mode: "contains"
      in_stock_contains: ["Add to Cart","Add to Bag"]
      out_of_stock_contains: ["Sold Out","Out of Stock"]

  - name: "PC – Phantasmal Flames Booster Bundle"
    url: "https://www.pokemoncenter.com/product/10-10191-109/"
    parse:
      mode: "contains"
      in_stock_contains: ["Add to Cart","Add to Bag"]
      out_of_stock_contains: ["Sold Out","Out of Stock"]
      
  - name: "PC – Phantasmal Flames Booster Box"
    url: "https://www.pokemoncenter.com/product/10-10190-119/"
    parse:
      mode: "contains"
      in_stock_contains: ["Add to Cart","Add to Bag"]
      out_of_stock_contains: ["Sold Out","Out of Stock"]

  - name: "Target – Destined Rivals Booster Bundle"
    url: "https://www.target.com/p/pok%C3%A9mon-trading-card-game-scarlet-38-violet-8212-destined-rivals-booster-bundle/-/A-94300067"
    parse:
      mode: "regex"
      # Considered IN STOCK if any of these appear in the HTML:
      pattern_in_stock: "(Add\\s*to\\s*cart|Ship\\s*it|Deliver\\s*it|Pickup\\s*here|Same\\s*Day\\s*Delivery)"
      # Considered OUT OF STOCK if any of these appear:
      pattern_out_of_stock: "(Sold\\s*out|Out\\s*of\\s*stock|Temporarily\\s*out\\s*of\\s*stock|Check\\s*back\\s*soon|Not\\s*available)"

 - name: "PC – ANY ETB in stock (category)"
  url: "https://www.pokemoncenter.com/category/elite-trainer-box"
  expand: "pc_category" 
  parse:
    mode: "regex"
    # Any of these indicate something is purchasable on the page:
    pattern_in_stock: "(Add\\s*to\\s*(cart|bag)|aria-label=\\\"Add to cart\\\"|data-automation-id=\\\"add-to-cart\\\"|btn--add-to-cart)"
    # Leave out-of-stock empty here; we just need a positive hit to open an Issue.
    pattern_out_of_stock: ""

 - name: "PC – ANY Booster Packs in stock (category)"
  url: "https://www.pokemoncenter.com/category/booster-packs"
  expand: "pc_category" 
  parse:
    mode: "regex"
    # Any of these indicate something is purchasable on the page:
    pattern_in_stock: "(Add\\s*to\\s*(cart|bag)|aria-label=\\\"Add to cart\\\"|data-automation-id=\\\"add-to-cart\\\"|btn--add-to-cart)"
    # Leave out-of-stock empty here; we just need a positive hit to open an Issue.
    pattern_out_of_stock: ""

 - name: "PC – ANY TCG Cards in stock (category)"
  url: "https://www.pokemoncenter.com/category/tcg-cards"
  expand: "pc_category" 
  parse:
    mode: "regex"
    # Any of these indicate something is purchasable on the page:
    pattern_in_stock: "(Add\\s*to\\s*(cart|bag)|aria-label=\\\"Add to cart\\\"|data-automation-id=\\\"add-to-cart\\\"|btn--add-to-cart)"
    # Leave out-of-stock empty here; we just need a positive hit to open an Issue.
    pattern_out_of_stock: ""

 - name: "PC – ANY Tins in stock (category)"
  url: "https://www.pokemoncenter.com/category/tcg-tins"
  expand: "pc_category" 
  parse:
    mode: "regex"
    # Any of these indicate something is purchasable on the page:
    pattern_in_stock: "(Add\\s*to\\s*(cart|bag)|aria-label=\\\"Add to cart\\\"|data-automation-id=\\\"add-to-cart\\\"|btn--add-to-cart)"
    # Leave out-of-stock empty here; we just need a positive hit to open an Issue.
    pattern_out_of_stock: ""

- name: "PC – ANY Boxed Sets in stock (category)"
  url: "https://www.pokemoncenter.com/category/boxed-sets"
  expand: "pc_category" 
  parse:
    mode: "regex"
    # Any of these indicate something is purchasable on the page:
    pattern_in_stock: "(Add\\s*to\\s*(cart|bag)|aria-label=\\\"Add to cart\\\"|data-automation-id=\\\"add-to-cart\\\"|btn--add-to-cart)"
    # Leave out-of-stock empty here; we just need a positive hit to open an Issue.
    pattern_out_of_stock: ""

- name: "TEST – Always match"
  url: "https://www.pokemoncenter.com/"
  parse:
    mode: "regex"
    pattern_in_stock: "."
    pattern_out_of_stock: ""

- name: Smoke test: create issue via API
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO: ${{ github.repository }}
  run: |
    set -e
    code=$(curl -s -o /tmp/resp.json -w "%{http_code}" \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "Accept: application/vnd.github+json" \
      -d '{"title":"🔧 Actions smoke test","body":"If you see this, issue creation works."}' \
      https://api.github.com/repos/$REPO/issues)
    echo "HTTP $code"
    cat /tmp/resp.json
