name: Restock Watch

on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minute
  workflow_dispatch: {}

jobs:
  watch:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

- name: Run watcher
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_ISSUES }}   # use your new PAT here
    GITHUB_REPOSITORY: ${{ github.repository }}
    PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
    PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  run: |
    python watcher.py

