name: Restock Watch (continuous)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

concurrency:
  group: restockwatch-continuous
  cancel-in-progress: true

jobs:
  watch:
    runs-on: self-hosted
    timeout-minutes: 4320

    # 👉 Set ONE of these to the path you installed above.
    env:
      PYPATH: C:\Python311\python.exe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify Python exists (fail fast)
        shell: powershell
        run: |
          if (-not (Test-Path "${env:PYPATH}")) {
            Write-Error "Python not found at ${env:PYPATH}. Install it machine-wide or update PYPATH."
            exit 1
          }
          & "${env:PYPATH}" -V

      - name: Install deps
        shell: powershell
        run: |
          & "${env:PYPATH}" -m pip install --upgrade pip
          & "${env:PYPATH}" -m pip install -r requirements.txt

      - name: Loop every 60s
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER:  ${{ secrets.PUSHOVER_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          while ($true) {
            Write-Host "=== $(Get-Date) ==="
            & "${env:PYPATH}" watcher.py
            Start-Sleep -Seconds 60
          }
