name: Restock Watch (continuous)

on:
  workflow_dispatch: {}  # click "Run workflow" to start

permissions:
  contents: read
  issues: write

concurrency:
  group: restockwatch-continuous
  cancel-in-progress: true

jobs:
  watch:
    runs-on: self-hosted
    timeout-minutes: 4320  # ~72 hours

    env:
      # <-- If your Python path changes, update this one line:
      PYPATH: C:\Users\josep\AppData\Local\Programs\Python\Python313\python.exe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity check Python
        shell: powershell
        run: '& "${env:PYPATH}" -V'

      - name: Install deps
        shell: powershell
        run: |
          & "${env:PYPATH}" -m pip install --upgrade pip
          & "${env:PYPATH}" -m pip install -r requirements.txt

      - name: Loop every 60s
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER:  ${{ secrets.PUSHOVER_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          while ($true) {
            Write-Host "=== $(Get-Date) ==="
            & "${env:PYPATH}" watcher.py
            Start-Sleep -Seconds 60
          }
